services:
  prometheus:
    image: prom/prometheus:v2.44.0
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"  # Prometheus Web UI
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Prometheus configuration file
      - prometheus_data:/prometheus  # Persist data across restarts

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"  # Grafana Web UI
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Set admin password for Grafana
    volumes:
      - grafana_data:/var/lib/grafana  # Persist Grafana data across restarts

volumes:
  prometheus_data:
  grafana_data: